import type { Metadata } from "next";
import { font_heading, font_text } from "./utils/fonts";

import "./globals.css";
import Navbar from "./components/nav/Navbar";
import { Provider } from "./utils/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
  
      <body className={`${font_heading} ${font_text}  font-text `} >
        <Provider>

      <Navbar/>
        {children}
        <p className="font-heading">sprawdxmy jak to dziala </p>
        </Provider>
        </body>
    </html>
  );
}
